### ISSUE TITLE
Alacritty ebuild needs to be updated

### ISSUE THREAD

**Issue by DarkDefender** [trofi/slyfox-gentoo#3]
Alacritty bumped several package versions recently, so the current ebuild does not work anymore.

**Comment by trofi** [comment]
Regenerated. Thank you!

**Comment by DarkDefender** [comment]
Need an other bump again. :P

**Comment by trofi** [comment]
Done. Thank you!

**Comment by DarkDefender** [comment]
Thank you for the blazingly fast reponse!

**Comment by DarkDefender** [comment]
An other bump is needed... :P

**Comment by trofi** [comment]
Yeah. `dev-util/cargo-ebuild` seems to fail to parse current Cargo.toml.
I'll try to fix `dev-util/cargo-ebuild` at some point.

`USE=fetch-crates x11-terms/alacritty` should be a working workaround.

**Comment by DarkDefender** [comment]
Ok, thanks for the headsup! :)

**Comment by DarkDefender** [comment]
Hmm, I'm guessing that you meant `USE=fetch-crates emerge x11-terms/alacritty` ?
I seems like there has to be some kind of missunderstanding here as alacritty does not have a `fetch-creates` useflag. (And it still fails if I try to emerge with that command)

**Comment by trofi** [comment]
Finally got to bumping `cargo-ebuild` and regenerated `alacritty` ebuild.
